version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3.10"
        NODE_VERSION: "lts/*"

    volumes:
      - ..:/workspace:cached

    command: sleep infinity
    ports:
      - 8000:8000

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres 
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  
  celery:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db
      - redis
      - app
    working_dir: /workspace
    command: celery -A mysuperblog worker -l info

  flower:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - FLOWER_PORT=5566
    working_dir: /workspace
    command: "celery -A mysuperblog flower"
    ports:
      - 5566:5566
    depends_on:
      - celery
      - redis

volumes:
  postgres-data: